version: '3'

services:
  wellness-sql:
    container_name: sql
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL__PASSWORD}
      - MSSQL_PID=${SQL__PID}
      - TZ=Europe/Belgrade 
    ports:
      - 1401:1433
    expose:
      - 1433
    networks:
      - wellness_network
      

  wellness-rabbitmq: 
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: unless-stopped
    ports: 
      - 8080:15672
      - 5672:5672
    expose:
      - 5672
    networks:
      - wellness_network
    environment:
      - TZ=Europe/Belgrade 
      - RABBITMQ_USERNAME=${RABBITMQ__USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ__PASSWORD}
    

  wellness-rabbitmq-service:
    container_name: rabbitmq-service
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile_rabbitmq
    ports:
      - 5000:${SIGNAL__R__PORT}
    networks:
      - wellness_network
    depends_on:
      - wellness-rabbitmq
    environment:
      - TZ=Europe/Belgrade 
      - SMTP_SERVER=${SMTP__SERVER}
      - SMTP_PORT=${SMTP__PORT}
      - SMTP_USERNAME=${SMTP__USERNAME}
      - SMTP_PASSWORD=${SMTP__PASSWORD}
      - RABBITMQ_HOST=${RABBITMQ__HOST}
      - RABBITMQ_USERNAME=${RABBITMQ__USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ__PASSWORD}
      - SIGNAL_R_PORT=${SIGNAL__R__PORT}

  wellness-payment-service:
    container_name: payment-service
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile_payments
    environment:
      - TZ=Europe/Belgrade 
      - ConnectionStrings__DefaultConnection=Server=wellness-sql,1433;Database=${SQL__DATABASE};User=${SQL__USER};Password=${SQL__PASSWORD};Trust Server Certificate=true;ConnectRetryCount=0
      - ASPNETCORE_ENVIRONMENT=Development
      - SMTP_SERVER=${SMTP__SERVER}
      - SMTP_PORT=${SMTP__PORT}
      - SMTP_USERNAME=${SMTP__USERNAME}
      - SMTP_PASSWORD=${SMTP__PASSWORD}
      - Stripe__PubKey=${STRIPE__PUBKEY}
      - Stripe__SecretKey=${STRIPE__SECRETKEY}
      - Paypal__ClientId=${PAYPAL__CLIENTID}
      - Paypal__Secret=${PAYPAL__SECRET}
      - RABBITMQ_HOST=${RABBITMQ__HOST}
      - RABBITMQ_USERNAME=${RABBITMQ__USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ__PASSWORD}
      - SIGNAL_R_PORT=${SIGNAL__R__PORT}
      
    ports:
      - "7012:80" 
    expose:
      - 7012
    networks:
      - wellness_network

  wellness-api:
    container_name: api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile_api
    environment:
      - TZ=Europe/Belgrade 
      - ConnectionStrings__DefaultConnection=Server=wellness-sql,1433;Database=${SQL__DATABASE};User=${SQL__USER};Password=${SQL__PASSWORD};Trust Server Certificate=true;ConnectRetryCount=0
      - ASPNETCORE_ENVIRONMENT=Development
      - AppSettings__Token=${APPSETTINGS__TOKEN}
      - SMTP_SERVER=${SMTP__SERVER}
      - SMTP_PORT=${SMTP__PORT}
      - SMTP_USERNAME=${SMTP__USERNAME}
      - SMTP_PASSWORD=${SMTP__PASSWORD}
      - RABBITMQ_HOST=${RABBITMQ__HOST}
      - RABBITMQ_USERNAME=${RABBITMQ__USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ__PASSWORD}
      - SIGNAL_R_PORT=${SIGNAL__R__PORT}
    ports:
      - 7081:7081
    networks:
      - wellness_network
    depends_on:
      - wellness-sql
      - wellness-rabbitmq-service

networks:
  wellness_network:
    driver: bridge
