# Koristi oficijelni .NET SDK image kao osnovu
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

# Postavi radni direktorijum unutar Docker kontejnera
WORKDIR /src
EXPOSE 80
EXPOSE 443

# Kopiraj csproj i restore-uj zavisnosti
COPY ["wellness.RabbitMQ/wellness.RabbitMQ.csproj", "wellness.RabbitMQ/"]
RUN dotnet restore "wellness.RabbitMQ/wellness.RabbitMQ.csproj"

# Kopiraj sve ostalo i build-uj aplikaciju
COPY . .
WORKDIR "/src/wellness.RabbitMQ"
RUN dotnet build "wellness.RabbitMQ.csproj" -c Release -o /app/build

# Izgradi i objavi aplikaciju
FROM build AS publish
RUN dotnet publish "wellness.RabbitMQ.csproj" -c Release -o /app/publish /p:UseAppHost=false

# Koristi oficijelni .NET ASP.NET Runtime image za izvršavanje aplikacije
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=publish /app/publish .

# Entry point za izvršavanje aplikacije
ENTRYPOINT ["dotnet", "wellness.RabbitMQ.dll"]
